apiVersion: apps/v1
kind: Deployment
metadata:
  name: plur-push-deployment
  namespace: plur-push
  labels:
    app.kubernetes.io/name: plur-push
    app.kubernetes.io/part-of: plur-push
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: plur-push
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plur-push
        app.kubernetes.io/part-of: plur-push
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: my-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          env:
            - name: RUST_LOG
              value: INFO
            - name: PLUR_PUSH__NOSTR__RELAY_URL
              value: wss://communities.nos.social
            - name: PLUR_PUSH__SERVICE__PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: plur-push-secret
                  key: app-nip29-relay-private-key
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: plur-push-secret
                  key: redis-connection-string
            - name: PLUR_PUSH__FCM__PROJECT_ID
              value: plur-623b0
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/secrets/serviceAccountKey.json
            # Firebase Web Configuration (from ConfigMap)
            - name: FIREBASE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_API_KEY
            - name: FIREBASE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_AUTH_DOMAIN
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_STORAGE_BUCKET
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_MESSAGING_SENDER_ID
            - name: FIREBASE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_APP_ID
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: google-application-credentials
              mountPath: /app/secrets
      volumes:
        - name: google-application-credentials
          secret:
            secretName: plur-push-secret
            items:
              - key: google-application-credentials
                path: serviceAccountKey.json


                