[server]
host = "0.0.0.0"
port = 8000

[relay]
url = "wss://communities.nos.social"

[nip29]
# Leave empty to disable NIP-29 features
private_key = ""

[redis]
url = "redis://127.0.0.1:6379"

[fcm]
# FCM credentials will be loaded from environment variables