apiVersion: v1
kind: ConfigMap
metadata:
  name: plur_push-config
  namespace: plur_push
data:
  config: |



    # listen: "REPLACED_BY_ENV"
    # database: "REPLACED_BY_ENV"
    # filesystem:
    #   storage_dir: "REPLACED_BY_ENV"
    # max_upload_bytes: 0
    # public_url: "REPLACED_BY_ENV"
    # nip29_relay:
    #   url: "REPLACED_BY_ENV"
    #   private_key: "REPLACED_BY_ENV"
    #   cache_expiration: 0
