apiVersion: apps/v1
kind: Deployment
metadata:
  name: plur_push-deployment
  namespace: plur_push
  labels:
    app.kubernetes.io/name: plur_push
    app.kubernetes.io/part-of: plur_push
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: plur_push
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plur_push
        app.kubernetes.io/part-of: plur_push
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: my-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          env:
            - name: APP__LISTEN
              value: 0.0.0.0:8000
            - name: APP__FILESYSTEM__STORAGE_DIR
              value: /app/data
            - name: APP__MAX_UPLOAD_BYTES
              value: "5000000000"
            - name: APP__PUBLIC_URL
              value: http://localhost:8000
            - name: APP__NIP29_RELAY__URL
              value: wss://communities.nos.social
            - name: APP__NIP29_RELAY__CACHE_EXPIRATION
              value: "300"
            - name: APP__NIP29_RELAY__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: "plur_push-secret"
                  key: example-secret-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1028Mi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: plur_push-config
              mountPath: /app/config.yaml
              subPath: config
      volumes:
        - name: plur_push-config
          configMap:
            name: plur_push-config
