apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: plur-push-hpa
  namespace: plur-push
  labels:
    app.kubernetes.io/part-of: plur-push
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plur-push-deployment
  minReplicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default 10 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage | default 80 }}
