{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plur-push-ingress
  namespace: plur-push
  labels:
    app.kubernetes.io/part-of: plur-push
    app.kubernetes.io/managed-by: Helm
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: plur-push-certificate
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plur-push-service
                port:
                  number: 80
  ingressClassName: {{ .Values.ingress.className }}
{{- end -}}