apiVersion: v1
kind: Service
metadata:
  name: plur-push-service
  namespace: plur-push
  labels:
    app.kubernetes.io/part-of: plur-push
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: plur-push
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP