replicaCount: 1
image:
  repository: ghcr.io/verse-pbc/nostr_push_service
  tag: "0.1.20251020-1435-6254f74" # Uses Chart.AppVersion when empty
  pullPolicy: Always
pdb:
  minAvailable: 1
autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  host: "nostrpush.verse.app"
