replicaCount: 1
image:
  repository: ghcr.io/verse-pbc/plur_push_service
  tag: "0.0.1-62" # Uses Chart.AppVersion when empty
  pullPolicy: Always
pdb:
  minAvailable: 1
autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: "nginx"
  host: "plurpush.verse.app"
