apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nostr-push-certificate
  namespace: nostr-push
  labels:
    app.kubernetes.io/part-of: nostr-push
    app.kubernetes.io/managed-by: Helm
spec:
  secretName: nostr-push-certificate
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - cert-manager
  dnsNames:
    - plurpush.verse.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
