apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-push-deployment
  namespace: nostr-push
  labels:
    app.kubernetes.io/name: nostr-push
    app.kubernetes.io/part-of: nostr-push
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nostr-push
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nostr-push
        app.kubernetes.io/part-of: nostr-push
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: my-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          env:
            - name: RUST_LOG
              value: INFO
            - name: APP_ENV
              value: production
            - name: FRONTEND_APP
              value: universes
            - name: NOSTR_PUSH__NOSTR__RELAY_URL
              value: wss://communities2.nos.social
            - name: NOSTR_PUSH__SERVICE__PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: nostr-push-secret
                  key: app-nip29-relay-private-key
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: nostr-push-secret
                  key: redis-connection-string
            # Firebase Web Configuration (from ConfigMap)
            - name: FIREBASE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_API_KEY
            - name: FIREBASE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_AUTH_DOMAIN
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_STORAGE_BUCKET
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_MESSAGING_SENDER_ID
            - name: FIREBASE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_APP_ID
            - name: FIREBASE_VAPID_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: firebase-web-config
                  key: FIREBASE_VAPID_PUBLIC_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: firebase-credentials
              mountPath: /app/secrets
      volumes:
        - name: firebase-credentials
          secret:
            secretName: nostr-push-secret
            items:
              - key: firebase-nostrpushdemo-credentials
                path: firebase-nostrpushdemo.json
              - key: firebase-universes-credentials
                path: firebase-universes.json
              - key: firebase-peek-credentials
                path: firebase-peek.json


                