apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nostr-push-pdb
  namespace: nostr-push
  labels:
    app.kubernetes.io/part-of: nostr-push
    app.kubernetes.io/managed-by: Helm
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nostr-push
