apiVersion: v1
kind: Service
metadata:
  name: nostr-push-service
  namespace: nostr-push
  labels:
    app.kubernetes.io/part-of: nostr-push
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: nostr-push
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
